apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWrite
  resources:
    requests:
      storage: 1Gi

apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        -image: mysql:8

