apiVersion : v1
kind : ConfigMap
metadata:
  name : mysql-configmap
data:
  host: mysql-svc:3306
#  host: my.database.host:3306
#  host: 10.244.0.131:3306 # pod IP
#  host: 10.109.201.118:3306 # mysql-svc DNS address
  name: onlineshopping
